server:
  servlet:
    context-path: /api/identity-service

spring:
  application:
    name: tpi-hometest
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${IDENTITY_DB_NAME:identity-service}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_USER_PW:123456}
  jpa:
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: ${ENABLED_LIQUIBASE:true}

logging:
  level:
    root: INFO
    com.preschool: ${APPLICATION_LOG_LEVEL:DEBUG}